929-Update_voyager_2_dummy_data_generation_function
ONS-SST/cis-fake-data pull request #11
Opened 2021-09-24 09:17 UTC by Ohi89

Things I have done: 
- insert 20% None's into barcode lists: DONE
- drop some swab and blood barcodes from list before using: done by slicing a 1/5 of the records before executing `generate_survey_v2_data()`
- all datetimes should be within 10 day range (tailored to date range logic): Created a new function based on the mimesis random date generation in helpers.py named `random_date_between()`

2021-09-24 09:48 UTC, foster999 requested changes
Have made a couple of suggested changes here, as I'm not sure these functions work as expected

2021-09-24 09:48 UTC, foster999 commented on example_data/households.py
> +    def slicer_to_null(input_list, step=5):
This approach introduces null values, meaning that our final null proportion will be 20% (from here)+ 16% (from the `null_prop` within the schema). Sorry, I realised that the "some" part of the specification was quite ambiguous too!

Lets say we want to drop roughly 10% of these, it might be easiest to just slice the first/last tenth off the list? Something like this might work for a quick implementation:
```
barcodes[int(len(barcodes))/10:]
```

2021-09-24 09:48 UTC, foster999 commented on example_data/helpers.py
> +    month = random.randint(start[1], end[1])
In an example where there start and end year are different, but the month and day are the same (e.g. Jan 1st), this would produce only dates on the 1st Jan for years between the start and end year.

[This implementation](https://stackoverflow.com/a/8170651/8103477) might do the job, taking a `datetime` object as start and end parameters.

2021-09-24 11:07 UTC, Ohi89 commented on example_data/households.py
> +    def slicer_to_null(input_list, step=5):
I added a slice to the 10% of the first barcodes of the list.

swab_barcode = swab_barcode[int(round(len(swab_barcode)/10)):]

2021-09-24 14:27 UTC, Ohi89 commented on example_data/helpers.py
> +    month = random.randint(start[1], end[1])
I used the function that converts datetime object into random now.

2021-09-27 08:55 UTC, foster999 approved these changes
The script was calling out of date functions for the lab files, so I've switched to call the more up to date ones and deleted the old ones

Thanks for making the changes, I think this is good to go now

2021-09-27 09:16 UTC, merged